import type { WorkQueueEntryView } from '@/components/projects/workQueue/workQueuePresentation';
import type { ProjectCommandStaffSummary } from '@/lib/projects/commandCentre/types';

const PROJECT_IDS = {
  overdue: '00000000-0000-4000-8000-000000000101',
  today: 'proj_fixture_queue_today',
  upcoming: '00000000-0000-4000-8000-000000000103',
  blocked: '00000000-0000-4000-8000-000000000104',
  triage: '00000000-0000-4000-8000-000000000105',
} as const;

export const workQueueFixtureStaff: ProjectCommandStaffSummary[] = [
  {
    userId: '00000000-0000-4000-8000-000000000201',
    displayName: 'Fixture coordinator',
    email: null,
    accessRole: 'staff',
  },
];

export const workQueueFixtureEntries: WorkQueueEntryView[] = [
  {
    projectId: PROJECT_IDS.overdue,
    projectName: 'Harbour Courtyard Canopy',
    stage: 'contacted',
    group: 'overdue',
    actionKind: 'workItem',
    title: 'Send first enquiry email',
    reason: 'Manual email is overdue; no sent confirmation exists.',
    dueAt: '2026-07-28T02:00:00.000Z',
    priority: 'CRITICAL',
    blockedReason: null,
    effectiveAssignee: {
      kind: 'staff',
      userId: workQueueFixtureStaff[0].userId,
    },
    workItemId: '00000000-0000-4000-8000-000000000301',
    workItemRowVersion: 2,
    stateRowVersion: 1,
    sourceType: 'LEAD_CADENCE',
    sourceKey: `lead:first-email:${PROJECT_IDS.overdue}`,
    subjectKind: 'PROJECT',
    subjectId: PROJECT_IDS.overdue,
    href: `/staff/projects/${PROJECT_IDS.overdue}`,
  },
  {
    projectId: PROJECT_IDS.today,
    projectName: 'Ridgeview Pergola',
    stage: 'contacted',
    group: 'today',
    actionKind: 'specialist',
    title: 'Arrange the site visit',
    reason: 'The customer has been contacted and the normal next step is a site visit.',
    dueAt: null,
    priority: 'NORMAL',
    blockedReason: null,
    effectiveAssignee: {
      kind: 'staff',
      userId: workQueueFixtureStaff[0].userId,
    },
    workItemId: null,
    workItemRowVersion: null,
    stateRowVersion: 3,
    sourceType: null,
    sourceKey: `journey-site-visit:arrange:${PROJECT_IDS.today}`,
    subjectKind: 'PROJECT',
    subjectId: PROJECT_IDS.today,
    actionLabel: 'Arrange site visit',
    href: `/staff/schedule?view=site-visits&project=${PROJECT_IDS.today}`,
  },
  {
    projectId: PROJECT_IDS.upcoming,
    projectName: 'Kauri Lane Shelter',
    stage: 'sent',
    group: 'nextSevenBusinessDays',
    actionKind: 'stateReview',
    title: 'Review waiting project',
    reason: 'Supplier drawings are expected before the project wakes.',
    dueAt: '2026-08-05T21:00:00.000Z',
    priority: 'NORMAL',
    blockedReason: null,
    effectiveAssignee: {
      kind: 'staff',
      userId: workQueueFixtureStaff[0].userId,
    },
    workItemId: null,
    workItemRowVersion: null,
    stateRowVersion: 4,
    sourceType: null,
    sourceKey: null,
    subjectKind: 'PROJECT',
    subjectId: PROJECT_IDS.upcoming,
    href: `/staff/projects/${PROJECT_IDS.upcoming}`,
  },
  {
    projectId: PROJECT_IDS.blocked,
    projectName: 'Estuary Outdoor Room',
    stage: 'quoting',
    group: 'blocked',
    actionKind: 'workItem',
    title: 'Confirm fixing detail',
    reason: 'Resolve the supplier dependency before pricing can continue.',
    dueAt: '2026-07-31T02:00:00.000Z',
    priority: 'CRITICAL',
    blockedReason: 'Waiting for supplier engineering response.',
    effectiveAssignee: {
      kind: 'staff',
      userId: workQueueFixtureStaff[0].userId,
    },
    workItemId: '00000000-0000-4000-8000-000000000304',
    workItemRowVersion: 5,
    stateRowVersion: 2,
    sourceType: 'MANUAL',
    sourceKey: 'fixture:blocked-fixing-detail',
    subjectKind: 'PROJECT',
    subjectId: PROJECT_IDS.blocked,
    href: `/staff/projects/${PROJECT_IDS.blocked}`,
  },
  {
    projectId: PROJECT_IDS.triage,
    projectName: 'Northern Courtyard Cover',
    stage: 'contacted',
    group: 'needsTriage',
    actionKind: 'needsTriage',
    title: 'Needs triage',
    reason: 'A staff member must choose the project disposition and next obligation.',
    dueAt: null,
    priority: null,
    blockedReason: null,
    effectiveAssignee: { kind: 'unassigned' },
    workItemId: null,
    workItemRowVersion: null,
    stateRowVersion: 1,
    sourceType: null,
    sourceKey: null,
    subjectKind: 'PROJECT',
    subjectId: PROJECT_IDS.triage,
    href: `/staff/projects/${PROJECT_IDS.triage}`,
  },
];
