import path from 'node:path';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: [
      { find: /^@sp\/geometry\/(.*)$/, replacement: path.resolve(__dirname, 'packages/geometry/src') + '/$1.ts' },
      { find: '@sp/geometry', replacement: path.resolve(__dirname, 'packages/geometry/src/index.ts') },
      { find: /^@sp\/email-provider$/, replacement: path.resolve(__dirname, 'packages/email-provider/src/index.ts') },
      { find: /^@sp\/jobs$/, replacement: path.resolve(__dirname, 'packages/jobs/src/index.ts') },
      { find: /^@sp\/costing$/, replacement: path.resolve(__dirname, 'packages/costing/src/index.ts') },
      { find: /^@sp\/costing\/server$/, replacement: path.resolve(__dirname, 'packages/costing/src/server/index.ts') },
      { find: '@sp/theme', replacement: path.resolve(__dirname, 'packages/theme/src/index.ts') },
      { find: '@/lib/cn', replacement: path.resolve(__dirname, 'apps/marketing/lib/cn.ts') },
      { find: '@/lib/enquiryEstimate', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryEstimate.ts') },
      { find: '@/lib/enquiryBudgets', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryBudgets.ts') },
      { find: '@/lib/enquiryAttachmentPolicy', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryAttachmentPolicy.ts') },
      { find: '@/lib/enquiryStoredAttachments', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryStoredAttachments.ts') },
      { find: '@/lib/enquiryIntake', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryIntake.ts') },
      { find: '@/lib/enquiryContext', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryContext.ts') },
      { find: '@/lib/attribution', replacement: path.resolve(__dirname, 'apps/marketing/lib/attribution.ts') },
      { find: '@/lib/enquiryAttachments', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryAttachments.ts') },
      { find: '@/lib/enquiryFormContract', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquiryFormContract.ts') },
      { find: '@/lib/simpleCoverCalculator', replacement: path.resolve(__dirname, 'apps/marketing/lib/simpleCoverCalculator.ts') },
      { find: '@/lib/simpleCoverHandoff', replacement: path.resolve(__dirname, 'apps/marketing/lib/simpleCoverHandoff.ts') },
      { find: '@/lib/simpleCoverPricing.server', replacement: path.resolve(__dirname, 'apps/marketing/lib/simpleCoverPricing.server.ts') },
      { find: '@/lib/guidedJourneyContract', replacement: path.resolve(__dirname, 'apps/marketing/lib/guidedJourneyContract.ts') },
      { find: '@/lib/guidedJourneyContext', replacement: path.resolve(__dirname, 'apps/marketing/lib/guidedJourneyContext.ts') },
      { find: '@/lib/projectFinderContract', replacement: path.resolve(__dirname, 'apps/marketing/lib/projectFinderContract.ts') },
      { find: '@/lib/projectFinderContinuation', replacement: path.resolve(__dirname, 'apps/marketing/lib/projectFinderContinuation.ts') },
      { find: '@/lib/enquirySourceContext.server', replacement: path.resolve(__dirname, 'apps/marketing/lib/enquirySourceContext.server.ts') },
      { find: '@/lib/marketingPublicRequest', replacement: path.resolve(__dirname, 'apps/marketing/lib/marketingPublicRequest.ts') },
      { find: '@/lib/marketingConversionDelivery', replacement: path.resolve(__dirname, 'apps/marketing/lib/marketingConversionDelivery.ts') },
      { find: '@/lib/sharedEmails', replacement: path.resolve(__dirname, 'apps/marketing/lib/sharedEmails.ts') },
      { find: '@/lib/publicTokenAccess', replacement: path.resolve(__dirname, 'apps/marketing/lib/publicTokenAccess.ts') },
      { find: '@/lib/supabaseService', replacement: path.resolve(__dirname, 'apps/marketing/lib/supabaseService.ts') },
      { find: '@/lib/quotes/acceptToken', replacement: path.resolve(__dirname, 'apps/marketing/lib/quotes/acceptToken.ts') },
      { find: '@/lib/consent', replacement: path.resolve(__dirname, 'apps/marketing/lib/consent.ts') },
      { find: '@/lib/trackingRegion', replacement: path.resolve(__dirname, 'apps/marketing/lib/trackingRegion.ts') },
      { find: '@/components/ConsentProvider', replacement: path.resolve(__dirname, 'apps/marketing/components/ConsentProvider.tsx') },
      { find: '@/components/marketing-foundation', replacement: path.resolve(__dirname, 'apps/marketing/components/marketing-foundation/index.ts') },
      { find: '@/components/enquiry/EnquiryErrorSummary', replacement: path.resolve(__dirname, 'apps/marketing/components/enquiry/EnquiryErrorSummary.tsx') },
      { find: '@/components/seo-landing/types', replacement: path.resolve(__dirname, 'apps/marketing/components/seo-landing/types.ts') },
      { find: '@/components/simple-cover-calculator/SimpleCoverCalculator', replacement: path.resolve(__dirname, 'apps/marketing/components/simple-cover-calculator/SimpleCoverCalculator.tsx') },
      { find: '@/components/project-finder/ProjectFinderJourneyContext', replacement: path.resolve(__dirname, 'apps/marketing/components/project-finder/ProjectFinderJourneyContext.tsx') },
      { find: /^@\/lib\/email\/(.*)$/, replacement: path.resolve(__dirname, 'apps/marketing/lib/email') + '/$1' },
      { find: /^@\/emails\/(.*)$/, replacement: path.resolve(__dirname, 'apps/marketing/emails') + '/$1' },
      { find: '@/lib/quotes/publicQuote', replacement: path.resolve(__dirname, 'test/shims/marketing-publicQuote.ts') },
      { find: '@/lib/invoices/publicInvoice', replacement: path.resolve(__dirname, 'test/shims/marketing-publicInvoice.ts') },
      { find: /^@\/lib\/emails\/(.*)$/, replacement: path.resolve(__dirname, 'apps/portal/lib/emails') + '/$1' },
      { find: /^@\/lib\/projects\/(.*)$/, replacement: path.resolve(__dirname, 'apps/portal/lib/projects') + '/$1' },
      { find: /^@\/lib\/quotes\/(.*)$/, replacement: path.resolve(__dirname, 'apps/portal/lib/quotes') + '/$1' },
      { find: /^@\/app\/(.*)$/, replacement: path.resolve(__dirname, 'apps/portal/app') + '/$1' },
      { find: /^@\/components\/(.*)$/, replacement: path.resolve(__dirname, 'apps/portal/components') + '/$1' },
      { find: /^@\/src\/(.*)$/, replacement: path.resolve(__dirname, 'apps/portal/src') + '/$1' },
      { find: /^@\/lib\/(.*)$/, replacement: path.resolve(__dirname, 'apps/portal/lib') + '/$1' },
      { find: '@', replacement: path.resolve(__dirname) },
      { find: 'server-only', replacement: path.resolve(__dirname, 'test/shims/server-only.ts') },
    ],
  },
  css: {
    postcss: {
      plugins: [],
    },
  },
  test: {
    environment: 'jsdom',
    environmentOptions: {
      jsdom: {
        url: 'http://localhost',
      },
    },
    setupFiles: [path.resolve(__dirname, 'test/setup/jsdomSvgPolyfill.ts')],
  },
});
