import type { HouseRoofMaterial, Vector3 } from '../contracts';

export const WORLD_Z: Vector3 = { x: 0, y: 0, z: 1 };
export const DEFAULT_EAVE_HEIGHT_MM = 2400;
export const DEFAULT_ROOF_PITCH_DEG = 25;
export const DEFAULT_SOFFIT_DEPTH_MM = 450;
export const DEFAULT_FASCIA_HEIGHT_MM = 180;
export const DEFAULT_GUTTER_WIDTH_MM = 125;
export const DEFAULT_GUTTER_DEPTH_MM = 90;
export const DEFAULT_GUTTER_PROJECTION_MM = 125;
export const DEFAULT_EAVE_OVERHANG_MM = 450;
export const DEFAULT_WALL_SOLID_THICKNESS_MM = 90;
export const DEFAULT_ROOF_SOLID_THICKNESS_MM = 120;
export const DEFAULT_SOFFIT_SOLID_THICKNESS_MM = 10;
export const DEFAULT_FASCIA_SOLID_THICKNESS_MM = 18;
export const DEFAULT_HOUSE_ROOF_FEATURE_FLASHING_GIRTH_MM = 300;
export const DEFAULT_HOUSE_ROOF_FEATURE_FLASHING_WING_MM = 150;
export const DEFAULT_HOUSE_ROOF_FEATURE_FLASHING_THICKNESS_MM = 1;
export const DEFAULT_HOUSE_ROOF_FEATURE_FLASHING_SURFACE_OFFSET_MM =
  DEFAULT_HOUSE_ROOF_FEATURE_FLASHING_THICKNESS_MM / 2;
export const DEFAULT_HOUSE_ROOF_MATERIAL: HouseRoofMaterial = 'corrugated_iron';
export const DEFAULT_HOUSE_ROOF_MATERIAL_SURFACE_OFFSET_MM = 2;
export const DEFAULT_DECK_SURFACE_THICKNESS_MM = 40;
export const RIDGE_COLLAPSE_EPSILON_MM = 1;
export const ROOF_JOIN_EPSILON_MM = 1e-3;
export const ROOF_JOIN_FEATURE_MIN_LENGTH_MM = 5;
export const ROOF_REGION_MIN_AREA_MM2 = 25;
