import {test,expect} from '@playwright/test';
import {PerspectiveCamera,Vector3} from 'three';
test.use({hasTouch:true});
for(const width of [390,1440]) test('Ziptrak openings, finishes, position and enquiry at '+width,async({page,browser})=>{
  await page.setViewportSize({width,height:844});
  await page.goto('/configurator-preview');
  await page.getByRole('button',{name:'Essential only',exact:true}).click();
  await page.getByRole('button',{name:'Design your pergola',exact:false}).click();
  const controls=page.getByRole('region',{name:'Outdoor blinds',exact:true});
  await controls.getByRole('button',{name:/Front 1/}).click();
  await controls.getByRole('radio',{name:'Ziptrak blind',exact:true}).check();
  const canvas=page.locator('canvas');
  await expect(canvas).toHaveAttribute('data-camera',/perspective/);
  const state=JSON.parse((await canvas.getAttribute('data-camera'))!);
  const bounds=(await canvas.boundingBox())!;
  const camera=new PerspectiveCamera(state.fov,bounds.width/bounds.height,10,200000);
  camera.position.fromArray(state.position);camera.up.set(0,0,1);camera.lookAt(new Vector3().fromArray(state.target));camera.updateMatrixWorld();
  const hit=new Vector3(4500,2950,1000).project(camera);
  await page.mouse.click(bounds.x+(hit.x+1)*bounds.width/2,bounds.y+(1-hit.y)*bounds.height/2);
  await expect(controls.getByRole('button',{name:/Front 2/})).toHaveAttribute('aria-pressed','true');
  await controls.getByRole('button',{name:/Front 1/}).click();
  await expect(page.locator('[data-blind-count]')).toHaveAttribute('data-blind-count','1');
  await controls.getByRole('radio',{name:'Uncovered',exact:true}).check();
  await controls.getByRole('radio',{name:'Outward flashing',exact:true}).check();
  await controls.getByRole('radio',{name:'Flashing + inside pelmet',exact:true}).check();
  await controls.getByRole('combobox',{name:'Blind fabric range'}).selectOption('pvc');
  await controls.locator('summary').click();
  await controls.getByRole('button',{name:'Blind colour Tinted',exact:true}).click();
  const position=controls.getByRole('slider',{name:'Blind lowered percentage'});
  await position.focus();await position.press('Home');
  await expect(position).toHaveValue('0');await position.press('End');
  await page.getByRole('button',{name:'Plan',exact:true}).click();
  await page.getByRole('button',{name:'Select Left 1 opening',exact:true}).click();
  await controls.getByRole('radio',{name:'Ziptrak blind',exact:true}).check();
  await expect(controls.getByText(/Level 100 × 50 mm header/)).toBeVisible();
  await controls.getByRole('radio',{name:'Open triangle',exact:true}).check();
  await controls.getByRole('radio',{name:'Acrylic infill',exact:true}).check();
  await controls.getByRole('combobox',{name:'Blind fabric range'}).selectOption('urban');
  await controls.getByRole('button',{name:'Apply finish to all blinds'}).click();
  await expect(page.locator('[data-blind-count]')).toHaveAttribute('data-blind-count','2');
  await page.getByRole('button',{name:'3D',exact:true}).click();
  await page.getByRole('button',{name:'Edit sides',exact:true}).click();
  // Existing blinds remain directly selectable when Sides highlighting is off.
  const current=JSON.parse((await canvas.getAttribute('data-camera'))!);
  const area=(await canvas.boundingBox())!;
  camera.aspect=area.width/area.height;camera.fov=current.fov;camera.updateProjectionMatrix();
  camera.position.fromArray(current.position);camera.lookAt(new Vector3().fromArray(current.target));camera.updateMatrixWorld();
  const front=new Vector3(1500,2950,1000).project(camera);
  const point={x:area.x+(front.x+1)*area.width/2,y:area.y+(1-front.y)*area.height/2};
  if(width===390) {await page.touchscreen.tap(point.x,point.y);} else {await page.mouse.click(point.x,point.y);}
  await expect(controls.getByRole('button',{name:/Front 1/})).toHaveAttribute('aria-pressed','true');
  await controls.getByRole('slider',{name:'Blind lowered percentage'}).focus();
  await controls.getByRole('slider',{name:'Blind lowered percentage'}).press('Home');
  await controls.getByRole('button',{name:/Left 1/}).click();
  await page.getByRole('button',{name:'Edit sides',exact:true}).click();
  await page.mouse.click(point.x,point.y);
  await expect(controls.getByRole('button',{name:/Front 1/})).toHaveAttribute('aria-pressed','true');
  await controls.getByRole('slider',{name:'Blind lowered percentage'}).focus();
  await controls.getByRole('slider',{name:'Blind lowered percentage'}).press('End');
  await page.getByRole('button',{name:'Edit sides',exact:true}).click();
  await expect(page.locator('canvas')).toHaveAttribute('data-camera',/perspective/);
  await page.screenshot({path:'artifacts/configurator-preview/blinds-'+width+'.png'});
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(value:string)=>{(window as unknown as {copiedDesign:string}).copiedDesign=value;}}}));
  await page.getByRole('button',{name:'Copy design link',exact:true}).click();
  const url=await page.evaluate(()=>(window as unknown as {copiedDesign:string}).copiedDesign);
  expect(url).toContain('#design=3~');
  const recipient=await browser.newContext();
  try {const opened=await recipient.newPage();await opened.goto(url);await expect(opened.locator('[data-blind-count]')).toHaveAttribute('data-blind-count','2');} finally {await recipient.close();}
  await page.getByRole('link',{name:'Continue with this design',exact:true}).click();
  await page.getByText('Details',{exact:true}).click();
  await expect(page.getByText(/Ziptrak Front 1/).last()).toBeVisible();
  await page.reload();
  await expect(page.locator('[data-blind-count]')).toHaveAttribute('data-blind-count','2');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);
});
