import type { CSSProperties } from 'react';

export type ModuleDrawingSurface = 'card' | 'minimal' | 'sheet';

export const PREMIUM_MODULE_DRAWING_THEME = {
  color: {
    canvas: '#F6F6F2',
    paperAlt: '#F1F1EC',
    inkStrong: '#2F382F',
    inkMid: '#5D675C',
    inkLight: '#8A9387',
    accentOlive: '#7F897C',
    borderSoft: '#C7CDC1',
    panelFillSubtle: 'rgba(47, 56, 47, 0.018)',
    panelFillSoft: 'rgba(127, 137, 124, 0.08)',
    ghostLine: '#8A9387',
    houseFill: 'rgba(93, 103, 92, 0.05)',
    houseStroke: 'rgba(127, 137, 124, 0.26)',
  },
  line: {
    majorWidth: '0.50',
    majorEmphasisWidth: '0.54',
    minorWidth: '0.32',
    roofWidth: '0.20',
    annotationWidth: '0.15',
    dimensionWidth: '0.15',
    guideWidth: '0.12',
    hiddenWidth: '0.15',
    hiddenDash: '1.5 1.6',
    dimensionDash: 'none',
    guideDash: '0.9 1.7',
  },
  type: {
    labelSize: '2.34px',
    angleSize: '2.18px',
    dimensionSize: '2.56px',
    metaSize: '2.18px',
  },
  font: {
    sans:
      "'Neue Haas Grotesk Text Pro', 'Neue Haas Grotesk', var(--font-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif)",
    display:
      "'Neue Haas Grotesk Display Pro', 'Neue Haas Grotesk Text Pro', 'Neue Haas Grotesk', var(--font-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif)",
  },
} as const;

type CssVariableMap = Record<`--${string}`, string>;

const baseVariables: CssVariableMap = {
  '--mv-canvas': PREMIUM_MODULE_DRAWING_THEME.color.canvas,
  '--mv-paper-alt': PREMIUM_MODULE_DRAWING_THEME.color.paperAlt,
  '--mv-ink-strong': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-ink-mid': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-ink-light': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-accent-olive': PREMIUM_MODULE_DRAWING_THEME.color.accentOlive,
  '--mv-border-soft': PREMIUM_MODULE_DRAWING_THEME.color.borderSoft,
  '--mv-panel-fill-subtle': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSubtle,
  '--mv-panel-fill-soft': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSoft,
  '--mv-ghost-line': PREMIUM_MODULE_DRAWING_THEME.color.ghostLine,
  '--mv-line-primary': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-line-secondary': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-line-rhythm': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-line-annotation': PREMIUM_MODULE_DRAWING_THEME.color.accentOlive,
  '--mv-line-hidden': PREMIUM_MODULE_DRAWING_THEME.color.ghostLine,
  '--mv-dim': PREMIUM_MODULE_DRAWING_THEME.color.accentOlive,
  '--mv-text-primary': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-text-secondary': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-text-muted': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-house-fill': PREMIUM_MODULE_DRAWING_THEME.color.houseFill,
  '--mv-house-stroke': PREMIUM_MODULE_DRAWING_THEME.color.houseStroke,
  '--mv-structure-fill': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSubtle,
  '--mv-overhang-fill': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSoft,
  '--mv-line-major-width': PREMIUM_MODULE_DRAWING_THEME.line.majorWidth,
  '--mv-line-major-emphasis-width': PREMIUM_MODULE_DRAWING_THEME.line.majorEmphasisWidth,
  '--mv-line-minor-width': PREMIUM_MODULE_DRAWING_THEME.line.minorWidth,
  '--mv-line-roof-width': PREMIUM_MODULE_DRAWING_THEME.line.roofWidth,
  '--mv-line-annotation-width': PREMIUM_MODULE_DRAWING_THEME.line.annotationWidth,
  '--mv-line-dimension-width': PREMIUM_MODULE_DRAWING_THEME.line.dimensionWidth,
  '--mv-line-guide-width': PREMIUM_MODULE_DRAWING_THEME.line.guideWidth,
  '--mv-line-hidden-width': PREMIUM_MODULE_DRAWING_THEME.line.hiddenWidth,
  '--mv-dash-hidden': PREMIUM_MODULE_DRAWING_THEME.line.hiddenDash,
  '--mv-dash-dimension': PREMIUM_MODULE_DRAWING_THEME.line.dimensionDash,
  '--mv-dash-guide': PREMIUM_MODULE_DRAWING_THEME.line.guideDash,
  '--mv-text-label-size': PREMIUM_MODULE_DRAWING_THEME.type.labelSize,
  '--mv-text-angle-size': PREMIUM_MODULE_DRAWING_THEME.type.angleSize,
  '--mv-text-dimension-size': PREMIUM_MODULE_DRAWING_THEME.type.dimensionSize,
  '--mv-text-meta-size': PREMIUM_MODULE_DRAWING_THEME.type.metaSize,
  '--mv-font-sans': PREMIUM_MODULE_DRAWING_THEME.font.sans,
  '--mv-font-display': PREMIUM_MODULE_DRAWING_THEME.font.display,
  '--mv-focus-ring': 'rgba(70, 87, 67, 0.16)',
  '--mv-stage-border': 'rgba(127, 137, 124, 0.18)',
  '--mv-stage-bg': 'linear-gradient(180deg, rgba(246, 246, 242, 0.98), rgba(241, 241, 236, 0.9))',
  '--mv-svg-bg': 'rgba(246, 246, 242, 0.96)',
  '--mv-chip-border': 'rgba(127, 137, 124, 0.2)',
  '--mv-chip-bg': 'rgba(241, 241, 236, 0.96)',
  '--mv-chip-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-tab-border': 'rgba(127, 137, 124, 0.18)',
  '--mv-tab-bg': 'rgba(246, 246, 242, 0.96)',
  '--mv-tab-active-bg': 'rgba(127, 137, 124, 0.12)',
  '--mv-tab-active-text': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-tab-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-state-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-state-detail': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-meta-text': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-state-success-bg': 'rgba(93, 103, 92, 0.08)',
  '--mv-state-success-text': PREMIUM_MODULE_DRAWING_THEME.color.accentOlive,
  '--mv-state-warning-bg': 'rgba(127, 137, 124, 0.1)',
  '--mv-state-warning-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-card-shadow': '0 16px 36px rgba(47, 56, 47, 0.08)',
  '--mv-sheet-border': 'rgba(127, 137, 124, 0.28)',
  '--mv-sheet-border-soft': 'rgba(199, 205, 193, 0.95)',
  '--mv-sheet-text': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-sheet-muted': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-sheet-bg': 'linear-gradient(180deg, rgba(246, 246, 242, 0.995), rgba(246, 246, 242, 0.99))',
  '--mv-sheet-panel-bg': 'rgba(241, 241, 236, 0.98)',
  '--mv-sheet-panel-bg-soft': 'rgba(241, 241, 236, 0.98)',
  '--mv-sheet-panel-bg-strong': 'rgba(241, 241, 236, 0.99)',
  '--mv-sheet-panel-border-soft': 'rgba(199, 205, 193, 0.95)',
  '--mv-sheet-panel-border-strong': 'rgba(199, 205, 193, 0.98)',
  '--mv-sheet-scale-bg': 'rgba(241, 241, 236, 0.98)',
  '--mv-sheet-viewport-bg': 'rgba(255, 255, 255, 0.12)',
  '--mv-sheet-viewport-border': 'rgba(199, 205, 193, 0.9)',
  '--mv-sheet-shadow': '0 24px 48px rgba(47, 56, 47, 0.08)',
};

const surfaceVariables: Record<ModuleDrawingSurface, CssVariableMap> = {
  card: {},
  minimal: {
    '--mv-stage-border': 'transparent',
    '--mv-stage-bg': 'transparent',
    '--mv-svg-bg': 'transparent',
    '--mv-card-shadow': 'none',
  },
  sheet: {
    '--mv-stage-border': 'transparent',
    '--mv-stage-bg': 'transparent',
    '--mv-svg-bg': 'transparent',
    '--mv-card-shadow': 'none',
    '--mv-line-secondary': 'rgba(93, 103, 92, 0.74)',
    '--mv-line-rhythm': 'rgba(93, 103, 92, 0.58)',
    '--mv-line-annotation': 'rgba(127, 137, 124, 0.8)',
    '--mv-line-hidden': 'rgba(138, 147, 135, 0.52)',
    '--mv-dim': 'rgba(127, 137, 124, 0.78)',
    '--mv-text-secondary': 'rgba(93, 103, 92, 0.82)',
    '--mv-text-muted': 'rgba(93, 103, 92, 0.68)',
    '--mv-house-fill': 'rgba(93, 103, 92, 0.038)',
    '--mv-house-stroke': 'rgba(127, 137, 124, 0.22)',
    '--mv-structure-fill': 'rgba(47, 56, 47, 0.012)',
    '--mv-overhang-fill': 'rgba(127, 137, 124, 0.045)',
    '--mv-line-major-width': '0.58',
    '--mv-line-major-emphasis-width': '0.64',
    '--mv-line-minor-width': '0.22',
    '--mv-line-annotation-width': '0.11',
    '--mv-line-dimension-width': '0.12',
    '--mv-line-guide-width': '0.09',
    '--mv-line-hidden-width': '0.09',
    '--mv-dash-hidden': '1.4 1.8',
    '--mv-dash-guide': '0.8 1.9',
    '--mv-text-label-size': '2.26px',
    '--mv-text-angle-size': '2.06px',
    '--mv-text-dimension-size': '2.18px',
    '--mv-text-meta-size': '2.06px',
    '--mv-sheet-border-soft': 'rgba(199, 205, 193, 0.58)',
    '--mv-sheet-muted': 'rgba(93, 103, 92, 0.74)',
    '--mv-sheet-panel-bg': 'rgba(244, 244, 239, 0.88)',
    '--mv-sheet-panel-bg-soft': 'rgba(244, 244, 239, 0.8)',
    '--mv-sheet-panel-bg-strong': 'rgba(244, 244, 239, 0.92)',
    '--mv-sheet-panel-border-soft': 'rgba(199, 205, 193, 0.56)',
    '--mv-sheet-panel-border-strong': 'rgba(199, 205, 193, 0.76)',
    '--mv-sheet-scale-bg': 'rgba(244, 244, 239, 0.74)',
    '--mv-sheet-viewport-border': 'rgba(199, 205, 193, 0.56)',
    '--mv-sheet-shadow': '0 18px 38px rgba(47, 56, 47, 0.06)',
  },
};

export function moduleDrawingThemeCssVariables(surface: ModuleDrawingSurface): CSSProperties {
  return {
    ...baseVariables,
    ...surfaceVariables[surface],
  } as CSSProperties;
}
