import type { CSSProperties } from 'react';

export type ModuleDrawingSurface = 'card' | 'minimal' | 'sheet';

export const PREMIUM_MODULE_DRAWING_THEME = {
  color: {
    canvas: '#F7F7F3',
    paperAlt: '#F1F2EC',
    inkStrong: '#2F382F',
    inkMid: '#5F695E',
    inkLight: '#8A9386',
    accentOlive: '#465743',
    borderSoft: '#D9DED5',
    panelFillSubtle: 'rgba(70, 87, 67, 0.03)',
    panelFillSoft: 'rgba(70, 87, 67, 0.05)',
    ghostLine: 'rgba(95, 105, 94, 0.45)',
    houseFill: 'rgba(95, 105, 94, 0.08)',
    houseStroke: 'rgba(95, 105, 94, 0.24)',
  },
  line: {
    majorWidth: '0.42',
    majorEmphasisWidth: '0.46',
    minorWidth: '0.29',
    roofWidth: '0.21',
    annotationWidth: '0.18',
    dimensionWidth: '0.18',
    guideWidth: '0.12',
    hiddenWidth: '0.18',
    hiddenDash: '1.8 1.8',
    dimensionDash: '2.6 1.6',
    guideDash: '1.2 2.1',
  },
  type: {
    labelSize: '2.38px',
    angleSize: '2.18px',
    dimensionSize: '2.46px',
    metaSize: '2.18px',
  },
} as const;

type CssVariableMap = Record<`--${string}`, string>;

const baseVariables: CssVariableMap = {
  '--mv-canvas': PREMIUM_MODULE_DRAWING_THEME.color.canvas,
  '--mv-paper-alt': PREMIUM_MODULE_DRAWING_THEME.color.paperAlt,
  '--mv-ink-strong': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-ink-mid': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-ink-light': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-accent-olive': PREMIUM_MODULE_DRAWING_THEME.color.accentOlive,
  '--mv-border-soft': PREMIUM_MODULE_DRAWING_THEME.color.borderSoft,
  '--mv-panel-fill-subtle': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSubtle,
  '--mv-panel-fill-soft': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSoft,
  '--mv-ghost-line': PREMIUM_MODULE_DRAWING_THEME.color.ghostLine,
  '--mv-line-primary': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-line-secondary': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-line-hidden': PREMIUM_MODULE_DRAWING_THEME.color.ghostLine,
  '--mv-dim': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-text-primary': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-text-secondary': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-text-muted': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-house-fill': PREMIUM_MODULE_DRAWING_THEME.color.houseFill,
  '--mv-house-stroke': PREMIUM_MODULE_DRAWING_THEME.color.houseStroke,
  '--mv-structure-fill': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSubtle,
  '--mv-overhang-fill': PREMIUM_MODULE_DRAWING_THEME.color.panelFillSoft,
  '--mv-line-major-width': PREMIUM_MODULE_DRAWING_THEME.line.majorWidth,
  '--mv-line-major-emphasis-width': PREMIUM_MODULE_DRAWING_THEME.line.majorEmphasisWidth,
  '--mv-line-minor-width': PREMIUM_MODULE_DRAWING_THEME.line.minorWidth,
  '--mv-line-roof-width': PREMIUM_MODULE_DRAWING_THEME.line.roofWidth,
  '--mv-line-annotation-width': PREMIUM_MODULE_DRAWING_THEME.line.annotationWidth,
  '--mv-line-dimension-width': PREMIUM_MODULE_DRAWING_THEME.line.dimensionWidth,
  '--mv-line-guide-width': PREMIUM_MODULE_DRAWING_THEME.line.guideWidth,
  '--mv-line-hidden-width': PREMIUM_MODULE_DRAWING_THEME.line.hiddenWidth,
  '--mv-dash-hidden': PREMIUM_MODULE_DRAWING_THEME.line.hiddenDash,
  '--mv-dash-dimension': PREMIUM_MODULE_DRAWING_THEME.line.dimensionDash,
  '--mv-dash-guide': PREMIUM_MODULE_DRAWING_THEME.line.guideDash,
  '--mv-text-label-size': PREMIUM_MODULE_DRAWING_THEME.type.labelSize,
  '--mv-text-angle-size': PREMIUM_MODULE_DRAWING_THEME.type.angleSize,
  '--mv-text-dimension-size': PREMIUM_MODULE_DRAWING_THEME.type.dimensionSize,
  '--mv-text-meta-size': PREMIUM_MODULE_DRAWING_THEME.type.metaSize,
  '--mv-focus-ring': 'rgba(70, 87, 67, 0.16)',
  '--mv-stage-border': 'rgba(95, 105, 94, 0.18)',
  '--mv-stage-bg': 'linear-gradient(180deg, rgba(247, 247, 243, 0.98), rgba(241, 242, 236, 0.88))',
  '--mv-svg-bg': 'rgba(247, 247, 243, 0.96)',
  '--mv-chip-border': 'rgba(95, 105, 94, 0.18)',
  '--mv-chip-bg': 'rgba(70, 87, 67, 0.04)',
  '--mv-chip-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-tab-border': 'rgba(95, 105, 94, 0.18)',
  '--mv-tab-bg': 'rgba(247, 247, 243, 0.96)',
  '--mv-tab-active-bg': 'rgba(70, 87, 67, 0.1)',
  '--mv-tab-active-text': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-tab-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-state-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-state-detail': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-meta-text': PREMIUM_MODULE_DRAWING_THEME.color.inkLight,
  '--mv-state-success-bg': 'rgba(70, 87, 67, 0.08)',
  '--mv-state-success-text': PREMIUM_MODULE_DRAWING_THEME.color.accentOlive,
  '--mv-state-warning-bg': 'rgba(95, 105, 94, 0.1)',
  '--mv-state-warning-text': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-card-shadow': '0 16px 36px rgba(47, 56, 47, 0.08)',
  '--mv-sheet-border': 'rgba(47, 56, 47, 0.28)',
  '--mv-sheet-border-soft': 'rgba(95, 105, 94, 0.18)',
  '--mv-sheet-text': PREMIUM_MODULE_DRAWING_THEME.color.inkStrong,
  '--mv-sheet-muted': PREMIUM_MODULE_DRAWING_THEME.color.inkMid,
  '--mv-sheet-bg':
    'linear-gradient(180deg, rgba(247, 247, 243, 0.98), rgba(241, 242, 236, 0.98)), repeating-linear-gradient(0deg, rgba(47, 56, 47, 0.012), rgba(47, 56, 47, 0.012) 1px, transparent 1px, transparent 18px)',
  '--mv-sheet-panel-bg': 'rgba(247, 247, 243, 0.88)',
  '--mv-sheet-scale-bg': 'rgba(247, 247, 243, 0.72)',
  '--mv-sheet-viewport-bg': 'rgba(255, 255, 255, 0.5)',
  '--mv-sheet-viewport-border': 'rgba(95, 105, 94, 0.12)',
  '--mv-sheet-shadow': '0 24px 48px rgba(47, 56, 47, 0.12)',
};

const surfaceVariables: Record<ModuleDrawingSurface, CssVariableMap> = {
  card: {},
  minimal: {
    '--mv-stage-border': 'transparent',
    '--mv-stage-bg': 'transparent',
    '--mv-svg-bg': 'transparent',
    '--mv-card-shadow': 'none',
  },
  sheet: {
    '--mv-stage-border': 'transparent',
    '--mv-stage-bg': 'transparent',
    '--mv-svg-bg': 'transparent',
    '--mv-card-shadow': 'none',
  },
};

export function moduleDrawingThemeCssVariables(surface: ModuleDrawingSurface): CSSProperties {
  return {
    ...baseVariables,
    ...surfaceVariables[surface],
  } as CSSProperties;
}
