import type { SeoLandingPageConfig } from '@/components/seo-landing/types';

const faqItems = [
  { question: 'What is a pitched pergola?', answer: ['A mono-pitched pergola uses one roof plane falling from a high edge to a low edge. The simple silhouette places more emphasis on the exact height, fall, connection and drainage path.', 'Sanctuary develops those dimensions around the home, site and intended use.'] },
  { question: 'When does a mono-pitched pergola suit an Auckland home?', answer: ['A single roof plane can suit a restrained extension, a narrow eave condition or a site where drainage needs one clear direction.', 'Available attachment height, the low edge, doors, windows, roof depth and appearance from inside should be checked before the form is selected.'] },
  { question: 'Can a pitched pergola sit above existing doors or sliders?', answer: ['Often, but the high and low edges must be considered against door heads, eaves, soffits, cladding, flashings and the required roof fall.', 'Actual clearances and support conditions need site assessment.'] },
  { question: 'Can a pitched pergola be freestanding?', answer: ['Yes. A freestanding mono-pitched structure may be considered where attachment is unsuitable or an independent cover better serves the site.', 'Foundations, stability, drainage and the relationship to the nearby home still need to be resolved for the completed design.'] },
  { question: 'Which roofing works on a pitched pergola?', answer: ['Acrylic, solid and combination roof approaches can be considered where they suit the design. The selected product, required fall, support, junctions and drainage need to work together.', 'Acrylic decisions should also account for roof depth, orientation and adjoining-room daylight.'] },
  { question: 'Where does water go on a mono-pitched roof?', answer: ['Water travels down the single roof plane to the low-edge gutter, then through downpipes to the agreed discharge point.', 'Fall, guttering, flashings, overflow and discharge are project-specific design decisions.'] },
  { question: 'Can blinds or screens be added to a pitched pergola?', answer: ['Blinds, acrylic infill panels or slat screens can be considered where an exposed edge needs more protection or privacy.', 'Mounting, headboxes, controls, clearances and the effect on openness should be coordinated with the frame before fabrication.'] },
  { question: 'How much does a pitched pergola cost in Auckland?', answer: ['Cost depends on footprint, high and low edges, spans, supports, roof material, connection, foundations, drainage, access, finish, integrations and any engineering or approval work.', 'Send photos and rough dimensions for a first assessment with assumptions made clear.'] },
  { question: 'Will a pitched pergola need building consent?', answer: ['Requirements depend on the property and completed design. Area, height, attachment, structure and planning controls may all be relevant.', 'The approval pathway must be confirmed for the actual project.'] },
] as const;

export const pitchedPergolasConfig = {
  marker: 'pitched-pergolas-auckland', route: '/pitched-pergolas-auckland',
  description: 'Explore custom pitched pergolas in Auckland. Plan the high edge, low edge, roof fall, daylight, drainage and house connection as one restrained roof form.',
  schemaName: 'Pitched Pergolas Auckland', serviceName: 'Custom pitched pergola design and installation in Auckland', serviceType: 'Mono-pitched pergola design and installation',
  hero: { image: '/images/product-pitched-01.jpg', imageAlt: 'Custom mono-pitched pergola with a clean single roof plane', objectPosition: '50% 46%', eyebrow: 'Pitched pergolas in Auckland', title: 'One roof plane leaves nowhere for a weak line to hide', intro: 'A mono-pitched pergola looks simple because the high edge, low edge, fall and frame have been resolved together. Sanctuary sets that plane around the house connection, the doors below, the daylight inside and the path for rainwater.', primaryCta: 'Send the pitched project', secondaryCta: 'Follow the roof plane', secondaryHref: '#pitched-anatomy', proof: ['High and low edges resolved together', 'One clear drainage direction', 'Custom attached or freestanding design'] },
  blocks: [
    { kind: 'split-intro', id: 'pitched-discipline', eyebrow: 'Simple is not automatic', title: 'The fewer the lines, the more each line matters', paragraphs: [
      'A mono-pitched roof is read from the high attachment or support down to one low edge. Its restraint can suit a contemporary home, but only when the plane has enough fall without pushing the lower beam into doors, views or circulation.',
      'Roof depth matters too. A deeper plane increases the distance between its high and low points and changes the light reaching rooms beside the deck.',
      'The design task is to find a fall, height and proportion that work technically and still feel calm from inside and outside.',
    ] },
    { kind: 'editorial-image', id: 'pitched-anatomy', tone: 'neutral', eyebrow: 'Read it from high edge to low edge', title: 'Four conditions define the single roof plane', image: { src: '/images/project-velskov-02.jpg', alt: 'Side view of a shallow-pitch pergola beneath a forest canopy', objectPosition: '50% 48%' }, lead: 'A section drawing tells more than the roof label.', items: [
      { title: 'High edge', text: 'Attachment height or independent support establishes where the plane begins and how it relates to the house.' },
      { title: 'Low edge', text: 'The lower beam and gutter need clear headroom, a controlled view and enough space for the intended use below.' },
      { title: 'Fall and depth', text: 'Roof projection and required fall work together, affecting height difference, drainage and the visual slope.' },
      { title: 'Direction', text: 'The roof sends water, shade and the eye toward one edge, so that edge must be deliberately placed and detailed.' },
    ] },
    { kind: 'projects', id: 'pitched-projects', eyebrow: 'One plane in different settings', title: 'Pitched pergolas can be quiet, layered or highly site-specific', intro: 'These projects show how the same basic roof logic changes with use, location and adjacent architecture.', items: [
      { slug: 'tindalls-bay-pavilion', label: 'Layered patio and carport roof', summary: 'Pitched roof zones weave around the existing home using insulated panels, acrylic roofing, battens and blinds where different conditions meet.' },
      { slug: 'velskov-forest', label: 'Shallow profile beneath the canopy', summary: 'A freestanding 7 m by 6 m pergola uses a shallow pitched roof to provide cover while keeping a low visual profile in the forest setting.' },
      { slug: 'waiheke-holiday-home', label: 'Outdoor cover in an exposed island setting', summary: 'The pergola project responds to a holiday-home context where house relationship, outlook and site exposure all influence the final scope.' },
      { slug: 'kiwi-rail-platform', label: 'Commercial platform cover', summary: 'A pitched commercial structure demonstrates how a single roof plane can organise a long, operationally focused covered area.' },
    ] },
    { kind: 'decision-cards', id: 'pitched-decisions', tone: 'warm', eyebrow: 'Follow the fall through the whole design', title: 'Four decisions keep a pitched roof precise', intro: 'The form succeeds when height, structure, material and water all move in the same direction.', items: [
      { title: 'Connection and high edge', outcome: 'A clear starting height and structural relationship to the home or independent supports.', consider: 'Cladding, fascia, soffit, roof edge, support, flashing, door heads and whether freestanding is preferable.' },
      { title: 'Low edge and outlook', outcome: 'A lower beam and gutter positioned without unnecessarily closing the room.', consider: 'Headroom, view, circulation, furniture, boundary conditions and the total roof depth.' },
      { title: 'Roofing and daylight', outcome: 'Acrylic, solid or combined roofing placed for the light and shade required.', consider: 'Orientation, adjoining windows, direct sun, underside character and exact product requirements.' },
      { title: 'Fall and drainage', outcome: 'One coordinated route from the high edge to gutter, downpipe and discharge.', consider: 'Required fall, roof junctions, flashings, guttering, overflow, discharge and maintenance access.' },
    ] },
    { kind: 'dark-cards', id: 'pitched-boundaries', eyebrow: 'A clean form still needs careful qualifications', title: 'The roof plane cannot answer every site question on its own', intro: 'Structure, weather edges and approval remain project-specific.', items: [
      { title: 'The low edge has a limit', text: 'A long projection and required fall may lower the outer edge. Feasible height must be checked against the actual house and use below.' },
      { title: 'The sides remain open', text: 'Overhead roofing manages rain on the plane, while wind-driven rain and low sun can enter at the open edges.' },
      { title: 'The span needs evidence', text: 'Post positions and member sizes depend on dimensions, loads, supports, exposure and any engineering required.' },
    ], links: [{ href: '/products/pergolas/pitched', label: 'Review the existing pitched product page' }, { href: '/acrylic-roof-pergolas-auckland', label: 'Review acrylic roof and daylight decisions' }] },
    { kind: 'numbered-cards', id: 'pitched-fit', eyebrow: 'Where restraint helps', title: 'A mono-pitch works best when its direction supports the brief', intro: 'Choose the form for what its single plane resolves.', items: [
      { title: 'A quiet extension is preferred', text: 'The roof can project from the building with a restrained silhouette and one clearly defined outer edge.' },
      { title: 'Height is available in the right place', text: 'The house or independent supports allow a useful high edge while preserving adequate height at the low edge.' },
      { title: 'Drainage benefits from one direction', text: 'The site provides a sensible low side for guttering, downpipes and the agreed discharge path.' },
    ] },
    { kind: 'process', id: 'pitched-process', eyebrow: 'From slope idea to buildable plane', title: 'Set the section before refining the surface', intro: 'The process tests whether one plane can meet both the practical and architectural brief.', items: [
      { title: 'Show the high and low context', copy: 'Send photos of the house edge, doors, ground and view, plus rough width, projection and intended use.' },
      { title: 'Assess available height and direction', copy: 'Sanctuary reviews attachment, clearances, likely fall, drainage edge, structure and site constraints.' },
      { title: 'Compare roof and edge options', copy: 'Roof material, frame, side protection and integrations are considered against light, exposure and openness.' },
      { title: 'Confirm the section and scope', copy: 'High and low edges, dimensions, products, structure, drainage, finish and responsibilities are documented.' },
      { title: 'Prepare and install', copy: 'The pergola is prepared and installed to the agreed design, with timing confirmed for the actual project.' },
    ] },
    { kind: 'scope', id: 'pitched-scope', eyebrow: 'Cost follows fall and connection', title: 'A pitched pergola scope needs both plan and section', lead: 'Footprint explains area. The high edge, low edge and support explain how the roof can be built.', paragraphs: ['Compare the same geometry, assembly, drainage and site responsibilities before comparing totals.'], factors: [
      ['Footprint and height difference', 'Width, projection, fall, high edge and low edge define the roof plane.'], ['Support and spans', 'Attachment, beams, posts, foundations and any engineering follow the completed structure.'], ['Roof and water management', 'Products, junctions, flashings, gutters, downpipes and discharge form one system.'], ['Finish and integrations', 'Coating, blinds, screens, lighting, heating, access and approvals add specific scope.'],
    ], checklistLead: 'Make the roof section legible in the quotation.', checklist: ['Width, projection and roof fall', 'High-edge and low-edge heights', 'Frame and structural materials', 'Roof product and finish', 'Connections, posts and foundations', 'Gutters, downpipes and discharge', 'Integrated options and trades', 'Engineering, approvals, assumptions and exclusions'] },
    { kind: 'faq', id: 'pitched-faq', tone: 'elevated', eyebrow: 'Questions along the roof plane', title: 'What to confirm before choosing a pitched pergola', intro: 'The final section depends on the house, site, selected products and completed design.', items: faqItems },
  ],
  finalCta: { eyebrow: 'Photograph both edges', title: 'Show where the roof could start and where it needs to finish', text: 'A straight-on photo can hide the height problem. Include side views, door heads, eaves, ground and the preferred drainage edge so the first assessment can follow the whole plane.', button: 'Send the pitched project', checklistTitle: 'Useful first inputs', checklist: ['Project suburb', 'House-edge and side-view photos', 'Views from inside', 'Rough width and projection', 'Approximate high and low clearances', 'Preferred drainage side, if known', 'Roof material preference', 'Plans or sketches'] },
  form: { ariaLabel: 'Pitched pergola project enquiry form', eyebrow: 'Start with both edges', heading: 'Send your pitched pergola project', intro: 'Share the house connection, doors, side views and rough dimensions. You can leave the exact fall, support and roof material open for assessment.', submitLabel: 'Send the pitched project', roofPreference: { label: 'Possible roof approach', detailKey: 'roofPreference', options: [
    { label: 'Acrylic roofing', value: 'Acrylic roofing', roofMaterials: ['acrylic'] }, { label: 'Solid or lined roofing', value: 'Solid or lined roofing', roofMaterials: ['timber'] }, { label: 'Combination roofing', value: 'Combination roofing', roofMaterials: ['acrylic', 'timber'] }, { label: 'Unsure', value: 'Unsure', roofMaterials: [] },
  ] } },
} satisfies SeoLandingPageConfig;
