import type { PortalScenarioId } from './portalScenarioRegistry';

type PortalRouteCategory = 'core' | 'project' | 'commercial' | 'schedule' | 'workbench' | 'admin' | 'diagnostic';

type PortalRouteRequiredRole = 'public' | 'staff' | 'admin' | 'fixture';

type PortalRouteDataRequirement =
  | 'none'
  | 'visible_project'
  | 'project_id'
  | 'estimate_id'
  | 'quote_id'
  | 'redirect_only'
  | 'fixture_flag'
  | 'admin_role'
  | 'scenario_required';

export type PortalRouteSmokeStatus = 'agent-access' | 'scenario-required' | 'admin-only' | 'fixture-only' | 'catalog-only';

export type PortalRouteDebugExportStatus = 'exported' | 'planned' | 'not-applicable';

type PortalShellMarker = 'public-auth-shell' | 'portal-shell' | 'admin-shell' | 'fixture-shell';

export interface PortalRouteCatalogEntry {
  id: string;
  category: PortalRouteCategory;
  routePattern: string;
  runnableRoute?: string;
  requiredRole: PortalRouteRequiredRole;
  ownerDoc: string;
  expectedHeading?: string;
  expectedShell: PortalShellMarker;
  dataRequirement: PortalRouteDataRequirement;
  smokeStatus: PortalRouteSmokeStatus;
  debugExportStatus: PortalRouteDebugExportStatus;
  scenarioId?: PortalScenarioId;
  notes: string;
}

export const portalRouteCatalog = [
  {
    id: 'root-redirect',
    category: 'core',
    routePattern: '/',
    requiredRole: 'staff',
    ownerDoc: 'docs/platform-workflow.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'redirect_only',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Compatibility entry redirects to the authenticated Dashboard.',
  },
  {
    id: 'login',
    category: 'core',
    routePattern: '/login',
    runnableRoute: '/login',
    requiredRole: 'public',
    ownerDoc: 'docs/environment-auth-supabase.md',
    expectedHeading: 'Staff Login',
    expectedShell: 'public-auth-shell',
    dataRequirement: 'none',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Canonical public staff sign-in route using the Foundation public-auth surface.',
  },
  {
    id: 'access-status',
    category: 'core',
    routePattern: '/access-status',
    runnableRoute: '/access-status?state=lookup-failed',
    requiredRole: 'public',
    ownerDoc: 'docs/environment-auth-supabase.md',
    expectedHeading: 'Access check unavailable',
    expectedShell: 'public-auth-shell',
    dataRequirement: 'none',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Public no-access and lookup-failure recovery states share the Foundation auth shell.',
  },
  {
    id: 'dashboard',
    category: 'core',
    routePattern: '/dashboard',
    runnableRoute: '/dashboard',
    requiredRole: 'staff',
    ownerDoc: 'docs/platform-workflow.md',
    expectedHeading: 'Dashboard',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'agent-access',
    debugExportStatus: 'not-applicable',
    notes: 'Core authenticated landing page and pipeline summary.',
  },
  {
    id: 'ui-foundation',
    category: 'core',
    routePattern: '/staff/ui-foundation',
    runnableRoute: '/staff/ui-foundation',
    requiredRole: 'staff',
    ownerDoc: 'docs/ui-foundation.md',
    expectedHeading: 'UI Foundation',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'agent-access',
    debugExportStatus: 'not-applicable',
    notes: 'Protected live catalogue for portal tokens, primitives, workflow badges, and responsive patterns.',
  },
  {
    id: 'email-previews',
    category: 'core',
    routePattern: '/staff/email-previews',
    requiredRole: 'staff',
    ownerDoc: 'docs/automation-email-audit.md',
    expectedHeading: 'Email design workbench',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Fixture-only marketing autoresponder review; sending is additionally restricted to enabled Vercel preview deployments and one server-configured recipient.',
  },
  {
    id: 'qa-email-preview-workbench-fixture',
    category: 'diagnostic',
    routePattern: '/qa/email-preview-workbench-fixture',
    requiredRole: 'fixture',
    ownerDoc: 'docs/automation-email-audit.md',
    expectedHeading: 'Email design workbench',
    expectedShell: 'fixture-shell',
    dataRequirement: 'fixture_flag',
    smokeStatus: 'fixture-only',
    debugExportStatus: 'not-applicable',
    notes: 'Data-free visual QA mirror gated by ENABLE_PORTAL_QA_FIXTURES; its server QA endpoint uses the exact governed renderer and synthetic no-provider delivery responses.',
  },
  {
    id: 'projects-index',
    category: 'project',
    routePattern: '/staff/projects',
    runnableRoute: '/staff/projects',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedHeading: 'Projects',
    expectedShell: 'portal-shell',
    dataRequirement: 'visible_project',
    smokeStatus: 'agent-access',
    debugExportStatus: 'not-applicable',
    notes: 'Project list and current source for first visible project discovery.',
  },
  {
    id: 'project-create',
    category: 'project',
    routePattern: '/staff/projects/new',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedHeading: 'New Project',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Project creation form, including the nested contact-create flow.',
  },
  {
    id: 'contacts-index',
    category: 'project',
    routePattern: '/staff/contacts',
    runnableRoute: '/staff/contacts',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedHeading: 'Contacts',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'agent-access',
    debugExportStatus: 'not-applicable',
    notes: 'Contact list; deeper create/detail scenarios belong to seeded coverage.',
  },
  {
    id: 'contact-create',
    category: 'project',
    routePattern: '/staff/contacts/new',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedHeading: 'New Contact',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Standalone contact creation form.',
  },
  {
    id: 'contact-detail',
    category: 'project',
    routePattern: '/staff/contacts/:contactId',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'scenario_required',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Contact detail requires a visible contact discovered by an authenticated scenario.',
  },
  {
    id: 'schedule',
    category: 'schedule',
    routePattern: '/staff/schedule',
    runnableRoute: '/staff/schedule',
    requiredRole: 'staff',
    ownerDoc: 'docs/schedule.md',
    expectedHeading: 'Schedule',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'agent-access',
    debugExportStatus: 'planned',
    notes: 'Schedule shell plus readiness API are covered by auth-runtime.',
  },
  {
    id: 'project-detail',
    category: 'project',
    routePattern: '/staff/projects/:projectId',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'project_id',
    smokeStatus: 'scenario-required',
    debugExportStatus: 'exported',
    scenarioId: 'project-with-estimate',
    notes: 'Requires a known project id before reliable agent smoke coverage.',
  },
  {
    id: 'estimate-detail',
    category: 'commercial',
    routePattern: '/staff/projects/:projectId/estimate/:estimateId',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'estimate_id',
    smokeStatus: 'scenario-required',
    debugExportStatus: 'exported',
    scenarioId: 'project-with-estimate',
    notes: 'Requires a project with a durable estimate scenario.',
  },
  {
    id: 'quote-detail',
    category: 'commercial',
    routePattern: '/staff/projects/:projectId/quotes/:quoteId',
    requiredRole: 'staff',
    ownerDoc: 'docs/quotes-invoices-job-packs.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'quote_id',
    smokeStatus: 'scenario-required',
    debugExportStatus: 'exported',
    scenarioId: 'quote-ready',
    notes: 'Requires a quote-ready seeded scenario.',
  },
  {
    id: 'quote-print-redirect',
    category: 'commercial',
    routePattern: '/staff/projects/:projectId/quotes/:quoteId/print',
    requiredRole: 'staff',
    ownerDoc: 'docs/quotes-invoices-job-packs.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'quote_id',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Compatibility URL redirects to the canonical Commercial quote preview.',
  },
  {
    id: 'design-workbench',
    category: 'workbench',
    routePattern: '/staff/projects/:projectId/design-workbench',
    requiredRole: 'staff',
    ownerDoc: 'docs/design-workbench-architecture.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'project_id',
    smokeStatus: 'scenario-required',
    debugExportStatus: 'exported',
    scenarioId: 'workbench-multi-object',
    notes: 'Project-backed workbench coverage requires a known project/design state.',
  },
  {
    id: 'design-list',
    category: 'project',
    routePattern: '/staff/projects/design-packages',
    requiredRole: 'staff',
    ownerDoc: 'docs/design-list.md',
    expectedHeading: 'Drafting Queue',
    expectedShell: 'portal-shell',
    dataRequirement: 'scenario_required',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'planned',
    notes: 'Operational Design Packages route presented to staff as the Drafting Queue; seeded data is required for row-level smoke coverage.',
  },
  {
    id: 'running-jobs',
    category: 'project',
    routePattern: '/staff/projects/running-jobs',
    requiredRole: 'staff',
    ownerDoc: 'docs/running-jobs.md',
    expectedHeading: 'Running Jobs',
    expectedShell: 'portal-shell',
    dataRequirement: 'scenario_required',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'planned',
    notes: 'Operational spreadsheet; route is cataloged now and should join smoke after stable seeded data exists.',
  },
  {
    id: 'calculator',
    category: 'commercial',
    routePattern: '/staff/calculator',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedHeading: 'Calculator',
    expectedShell: 'portal-shell',
    dataRequirement: 'estimate_id',
    smokeStatus: 'scenario-required',
    debugExportStatus: 'planned',
    scenarioId: 'project-with-estimate',
    notes: 'Authenticated calculator trust coverage uses a valid V2 project estimate scenario.',
  },
  {
    id: 'staff-home-redirect',
    category: 'core',
    routePattern: '/staff',
    requiredRole: 'staff',
    ownerDoc: 'docs/platform-workflow.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'redirect_only',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Compatibility entry redirects to Dashboard.',
  },
  {
    id: 'staff-login-redirect',
    category: 'core',
    routePattern: '/staff/login',
    requiredRole: 'public',
    ownerDoc: 'docs/environment-auth-supabase.md',
    expectedShell: 'public-auth-shell',
    dataRequirement: 'redirect_only',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Preserves search parameters while redirecting to the canonical public login.',
  },
  {
    id: 'running-jobs-redirect',
    category: 'project',
    routePattern: '/staff/running-jobs',
    requiredRole: 'staff',
    ownerDoc: 'docs/running-jobs.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'redirect_only',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Compatibility URL redirects to the Projects-owned Running Jobs route.',
  },
  {
    id: 'old-calculator-redirect',
    category: 'commercial',
    routePattern: '/staff/old-calculator',
    requiredRole: 'staff',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'redirect_only',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Compatibility URL redirects to the canonical Calculator route.',
  },
  {
    id: 'sidebar-lab',
    category: 'diagnostic',
    routePattern: '/staff/sidebar-lab',
    requiredRole: 'staff',
    ownerDoc: 'docs/ui-foundation.md',
    expectedShell: 'portal-shell',
    dataRequirement: 'none',
    smokeStatus: 'catalog-only',
    debugExportStatus: 'not-applicable',
    notes: 'Protected diagnostic route for sidebar-state development; not a production workflow.',
  },
  {
    id: 'admin-home',
    category: 'admin',
    routePattern: '/admin',
    requiredRole: 'admin',
    ownerDoc: 'docs/environment-auth-supabase.md',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin-only shell; skip for the default staff test account.',
  },
  {
    id: 'admin-costing',
    category: 'admin',
    routePattern: '/admin/costing',
    requiredRole: 'admin',
    ownerDoc: 'docs/costing-and-geometry.md',
    expectedHeading: 'Costing control centre',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin-only Calculator Brain configuration, comparison, validation and publication control centre.',
  },
  {
    id: 'pricebook',
    category: 'admin',
    routePattern: '/pricebook',
    requiredRole: 'admin',
    ownerDoc: 'docs/costing-and-geometry.md',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin pricebook route; staff sessions may redirect to calculator.',
  },
  {
    id: 'admin-cost-materials',
    category: 'admin',
    routePattern: '/admin/costs/materials',
    requiredRole: 'admin',
    ownerDoc: 'docs/costing-and-geometry.md',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin cost material maintenance route.',
  },
  {
    id: 'admin-cost-actions',
    category: 'admin',
    routePattern: '/admin/costs/actions',
    requiredRole: 'admin',
    ownerDoc: 'docs/costing-and-geometry.md',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin install-action maintenance route.',
  },
  {
    id: 'admin-cost-overheads',
    category: 'admin',
    routePattern: '/admin/costs/overheads',
    requiredRole: 'admin',
    ownerDoc: 'docs/costing-and-geometry.md',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin overhead maintenance route.',
  },
  {
    id: 'admin-imports',
    category: 'admin',
    routePattern: '/admin/imports',
    requiredRole: 'admin',
    ownerDoc: 'docs/supabase-schema-map.md',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin import tooling; mutating flows need explicit scenario planning.',
  },
  {
    id: 'admin-access',
    category: 'admin',
    routePattern: '/admin/access',
    requiredRole: 'admin',
    ownerDoc: 'docs/environment-auth-supabase.md',
    expectedHeading: 'Access',
    expectedShell: 'admin-shell',
    dataRequirement: 'admin_role',
    smokeStatus: 'admin-only',
    debugExportStatus: 'planned',
    notes: 'Admin access and schedule-crew assignment route.',
  },
  {
    id: 'qa-design-workbench-fixture',
    category: 'diagnostic',
    routePattern: '/qa/design-workbench-fixture?fixture=:fixtureSlug',
    requiredRole: 'fixture',
    ownerDoc: 'docs/design-workbench-architecture.md',
    expectedShell: 'fixture-shell',
    dataRequirement: 'fixture_flag',
    smokeStatus: 'fixture-only',
    debugExportStatus: 'exported',
    notes: 'Hidden fixture route gated by ENABLE_SANCTUARY_GEOMETRY_WORKBENCH_FIXTURES.',
  },
  {
    id: 'qa-projects-index-mutation-fixture',
    category: 'diagnostic',
    routePattern: '/qa/projects-index-mutation-fixture',
    requiredRole: 'fixture',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedShell: 'fixture-shell',
    dataRequirement: 'fixture_flag',
    smokeStatus: 'fixture-only',
    debugExportStatus: 'not-applicable',
    notes: 'Data-free mutation timing route gated by ENABLE_PORTAL_QA_FIXTURES.',
  },
  {
    id: 'qa-project-page-shell-fixture',
    category: 'diagnostic',
    routePattern: '/qa/project-page-shell-fixture',
    requiredRole: 'fixture',
    ownerDoc: 'docs/projects-contacts-estimates-calculator.md',
    expectedShell: 'fixture-shell',
    dataRequirement: 'fixture_flag',
    smokeStatus: 'fixture-only',
    debugExportStatus: 'not-applicable',
    notes: 'Data-free Project Detail shell fixture gated by ENABLE_PORTAL_QA_FIXTURES.',
  },
  {
    id: 'qa-project-command-centre-fixture',
    category: 'diagnostic',
    routePattern: '/qa/project-command-centre-fixture',
    requiredRole: 'fixture',
    ownerDoc: 'docs/project-command-centre-architecture.md',
    expectedShell: 'fixture-shell',
    dataRequirement: 'fixture_flag',
    smokeStatus: 'fixture-only',
    debugExportStatus: 'exported',
    notes: 'Data-free command-centre state fixture gated by ENABLE_PORTAL_QA_FIXTURES.',
  },
  {
    id: 'qa-ui-foundation-fixture',
    category: 'diagnostic',
    routePattern: '/qa/ui-foundation-fixture',
    requiredRole: 'fixture',
    ownerDoc: 'docs/ui-foundation.md',
    expectedHeading: 'UI Foundation',
    expectedShell: 'fixture-shell',
    dataRequirement: 'fixture_flag',
    smokeStatus: 'fixture-only',
    debugExportStatus: 'not-applicable',
    notes: 'Data-free visual QA mirror gated by ENABLE_PORTAL_QA_FIXTURES; the staff route remains protected.',
  },
] as const satisfies readonly PortalRouteCatalogEntry[];

export const agentAccessSmokeRoutes = portalRouteCatalog.filter(
  (entry): entry is PortalRouteCatalogEntry & { runnableRoute: string; expectedHeading: string } =>
    entry.smokeStatus === 'agent-access' && Boolean(entry.runnableRoute) && Boolean(entry.expectedHeading),
);

export const agentScenarioSmokeRoutes = portalRouteCatalog.filter(
  (entry): entry is PortalRouteCatalogEntry & { scenarioId: PortalScenarioId } =>
    entry.smokeStatus === 'scenario-required' && Boolean(entry.scenarioId),
);
