import type {
  AiActivityTaskDetail,
  AiActivityTaskSummary,
} from '@/lib/ai/activityContract';

const taskId = '11111111-1111-4111-8111-111111111111';
const approvalId = '22222222-2222-4222-8222-222222222222';

export const aiActivityFixtureTasks: readonly AiActivityTaskSummary[] = [
  {
    taskId,
    taskType: 'synthetic.echo',
    agentKey: 'sanctuary.synthetic',
    agentVersion: '1.0.0',
    capabilityKey: 'synthetic.echo',
    capabilityVersion: '1.0.0',
    policyVersion: '1.0.0',
    objective: 'Verify the synthetic task control path',
    status: 'awaiting_approval',
    riskClass: 'low',
    dataClassification: 'internal',
    projectId: null,
    parentTaskId: null,
    maxCostCents: 0,
    actualCostCents: 0,
    failureCode: null,
    safeFailureSummary: null,
    createdAt: '2026-08-18T00:00:00.000Z',
    updatedAt: '2026-08-18T00:03:00.000Z',
    startedAt: '2026-08-18T00:01:00.000Z',
    completedAt: null,
  },
  {
    taskId: '33333333-3333-4333-8333-333333333333',
    taskType: 'synthetic.policy_check',
    agentKey: 'sanctuary.synthetic',
    agentVersion: '1.0.0',
    capabilityKey: 'synthetic.policy_check',
    capabilityVersion: '1.0.0',
    policyVersion: '1.0.0',
    objective: 'Prove a zero-cost policy evaluation',
    status: 'succeeded',
    riskClass: 'low',
    dataClassification: 'internal',
    projectId: null,
    parentTaskId: null,
    maxCostCents: 0,
    actualCostCents: 0,
    failureCode: null,
    safeFailureSummary: null,
    createdAt: '2026-08-17T23:00:00.000Z',
    updatedAt: '2026-08-17T23:02:00.000Z',
    startedAt: '2026-08-17T23:01:00.000Z',
    completedAt: '2026-08-17T23:02:00.000Z',
  },
];

export const aiActivityFixtureDetail: AiActivityTaskDetail = {
  task: aiActivityFixtureTasks[0],
  events: [
    {
      eventKey: '1',
      taskId,
      sequence: 1,
      eventType: 'created',
      fromStatus: null,
      toStatus: null,
      actorKind: 'human',
      actorKey: 'portal.staff',
      nodeId: null,
      safeSummary: 'Synthetic task recorded with no external effect.',
      occurredAt: '2026-08-18T00:00:00.000Z',
    },
    {
      eventKey: '2',
      taskId,
      sequence: 2,
      eventType: 'status_changed',
      fromStatus: 'proposed',
      toStatus: 'awaiting_approval',
      actorKind: 'agent',
      actorKey: 'sanctuary.synthetic',
      nodeId: null,
      safeSummary: 'Exact synthetic approval requested.',
      occurredAt: '2026-08-18T00:03:00.000Z',
    },
  ],
  approvals: [
    {
      approvalId,
      taskId,
      actionType: 'synthetic.effect',
      targetType: 'synthetic.fixture',
      targetId: 'echo_v1',
      payloadHash: `sha256:${'a'.repeat(64)}`,
      payloadSummary: 'Approve the exact zero-effect synthetic fixture.',
      requiredRole: 'admin',
      requestedByKind: 'agent',
      requestedByKey: 'sanctuary.synthetic',
      requestedAt: '2026-08-18T00:03:00.000Z',
      expiresAt: '2026-08-18T00:18:00.000Z',
      singleUse: true,
      impact: ['Records a synthetic approval decision only.', 'Creates no customer, project, or provider effect.'],
      validations: [
        { validationKey: 'synthetic.only', passed: true, evidenceId: null },
        { validationKey: 'effect.none', passed: true, evidenceId: null },
      ],
      status: 'expired',
      decision: null,
      decidedByRole: null,
      decidedAt: null,
      consumedAt: null,
      invalidationReasonCode: null,
    },
  ],
};
